apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: statestore
spec:
  type: state.azure.blobstorage
  version: v1
  metadata:
  - name: accountName
    value: "daprstatestor"
  - name: accountKey
    value: "<insert key here>"
  - name: containerName
    value: "<insert container name>"
